create table tab_identity (ID int auto_increment, 
DESCRITOR varchar(20),
primary key(ID));

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE 1');

SELECT * FROM TAB_IDENTITY;

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE 2');
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE 3');
INSERT INTO TAB_IDENTITY (ID, DESCRITOR) VALUES (NULL, 'CLIENTE 4');

DELETE FROM TAB_IDENTITY WHERE ID='5';
INSERT INTO TAB_IDENTITY (ID, DESCRITOR) VALUES (NULL, 'CLIENTE 5');
INSERT INTO TAB_IDENTITY (ID, DESCRITOR) VALUES (NULL, 'CLIENTE 6');
INSERT INTO TAB_IDENTITY (ID, DESCRITOR) VALUES (100, 'CLIENTE 7');
INSERT INTO TAB_IDENTITY (ID, DESCRITOR) VALUES (NULL, 'CLIENTE 8');
